GET http://127.0.0.1:8000/ HTTP/1.1
###

GET http://127.0.0.1:8000/register HTTP/1.1
###

POST http://127.0.0.1:8000/register HTTP/1.1
content-type: application/x-www-form-urlencoded

login=user1
&password=password1

###

GET http://127.0.0.1:8000/login HTTP/1.1
###

POST http://127.0.0.1:8000/login HTTP/1.1
content-type: application/x-www-form-urlencoded

login=user1
&password=password1

###

GET http://127.0.0.1:8000/activate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjYyNDAwODY3fQ.oNoUQzFItqBXMOh9RX1GxYq6YyTyfgqg7yFKw5zoFXU

###
GET http://127.0.0.1:8000/test/create

###
GET http://127.0.0.1:8000/products
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6InVzZXIxIn0.fPq-NhED3i71Ftvr_UsoZA7a0moBYkm3JctgeqIqi_M
###

GET http://127.0.0.1:8000/admin/products
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6InVzZXIxIn0.fPq-NhED3i71Ftvr_UsoZA7a0moBYkm3JctgeqIqi_M
###

GET http://127.0.0.1:8000/admin/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6InVzZXIxIn0.fPq-NhED3i71Ftvr_UsoZA7a0moBYkm3JctgeqIqi_M